print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/alexadorsey/Desktop/CSCI 526/CSCI526Project1/PaperPlains/Assets/ring.mb"`)
{		
	file -o "/Users/alexadorsey/Desktop/CSCI 526/CSCI526Project1/PaperPlains/Assets/ring.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/alexadorsey/Desktop/CSCI 526/CSCI526Project1/PaperPlains/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/alexadorsey/Desktop/CSCI 526/CSCI526Project1/PaperPlains/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/alexadorsey/Desktop/CSCI 526/CSCI526Project1/PaperPlains/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
